### PR TITLE
Support recurring gcal rotas with code from @ipmb

### PR DESCRIPTION
**Pull request by GregoryAveryWeir**
This is support for shift rotations via recurring events in iCalendar, discussed in issue #48. It's working for us so far, so I made a PR for it based on the code @ipmb links in that issue (last discussed in 2014).

### CODE REVIEW

**Comment by dbuxton** [comment]
@GregoryAveryWeir thanks for this. Great stuff.

Ideally it would be nice to have tests of some sort so we can check that the functionality works as advertised.

There is a very basic stub for duty rota tests in https://github.com/arachnys/cabot/blob/cd73f0d6d51ba3012ffcd484c138b733e4defdec/cabot/cabotapp/tests/tests_basic.py#L429 - could you add a small test just to make sure that this works for recurring events?

(It's easy to stub out the server responses if you copy that test - not the most elegant method but it works)

**Comment by GregoryAveryWeir** [comment]
@dbuxton How's that? It doesn't account for particularly complicated scenarios, but it covers the basics.

**Comment by dbuxton** [comment]
lgtm

@JeanFred can you merge if you're happy?

**Comment by JeanFred** [comment]
I fixed a couple of indentation and merged this manually − thanks for this @GregoryAveryWeir !

(Wow − you’re *the* Gregory Weir? It was quite a while back but I really loved _The Majesty of Colors_ :-)

**Comment by dbuxton** [comment]
@JeanFred thanks - and @GregoryAveryWeir thanks for the contribution.

**Comment by GregoryAveryWeir** [comment]
My pleasure! Thanks for the great tool and thanks to @ipmb for the vast bulk of the code.

(Yes, that's me, glad you liked it! And shameless plug, we're [doing a remastering for modern devices...](http://majestyofcolors.com/))

**Pull request closed without merging**
