### PR TITLE
Cabot Plugin system

### PR DESCRIPTION
**Pull request by bonniejools**
Hello all,

This is something that I've been working on for the past couple of weeks. It is almost finished however I'm going to have to take a short break to focus on end of year exams. This is reworking of Cabot's plugin system which will now support StatusCheck plugins. Other changes include:

* Upgrade to Django 1.9
* A new 'plugins' page which allow you to test alert plugins.
* More tests.
* A new user preferences page.

The new plugins are stored at https://github.com/cabotapp/ . The plugins are working and tested however there is still documentation to be done. My end of year exams are fast approaching so I'm taking a break however I am hoping to have this ready to merge by the end of the month. The only things left to do are documentation and migrations. I made a pull request for any comments or questions.

I welcome any comments,

Jonny

### CODE REVIEW

**Comment by bonniejools** [comment]
Commits will be squashed in time for merging.

**Comment by bonniejools** [comment]
The plugin system is now finished and working **for new installations**. I am going to look into doing the migrations this evening. The upgrade from South to the Django's builtin migration system means that the original migration schemes had to be removed and reset. This shouldn't be a problem but I'll take a look.

**Comment by dbuxton** [comment]
This sounds like a big change. (We obviously need to rebase to resolve merge commits). @JeanFred can you help @bonniejools work out how to make upgrades seamless?

**Comment by bonniejools** [comment]
Merge conflicts have been resolved. Can I request that no new pull requests are accepted for the next few days.

**Comment by JeanFred** [comment]
Thanks for this work @bonniejools  − must have been quite a ride to fix the merge conflicts too :)

Sure, let’s get this merged before merging other things. :)

**Comment by bonniejools** [comment]
I believe that the migrations are now working but I'll need to write some tests first to make sure. There are also a couple of other loose ends that need to be sorted out :)

**Comment by bonniejools** [comment]
The new plugin system is now complete :tada:

The only thing left to do is upload the new and updated plugins to PyPi since they are currently being installed straight from GitHub. The old plugins are owned by the Arachnys account so I'll need access to the Arachnys account temporarily in order to update the plugins (unless you want to do it yourselves). I've emailed @dbuxton about it.

**Comment by bonniejools** [comment]
bump

**Comment by JeanFred** [comment]
Hey @bonniejools, sorry for the delay.

I’ll look into setting up automatic releases to Pypi (using Travis) − would make things easier in the long run.

**Comment by JeanFred** [comment]
@bonniejools Could I get Owner access to @cabotapp organisation?

**Comment by JeanFred** [comment]
Yes, David just did it :)

**Comment by bonniejools** [comment]
Okay well let me know if there's anything that I can do

**Comment by dbuxton** [comment]
@bonniejools sorry that there hasn't been any motion on this, as discussed we'd be happy to merge as long as we can break out into somewhat-digestable mini-PRs that can land individually.

I'm going to close this for the moment but happy to reopen in the future.

**Comment by rewolf** [comment]
@bonniejools @dbuxton is this dead in the water? 
As a main priority Cabot really needs to get out of Django 1.6.   Is anyone working on doing that?

**Comment by dbuxton** [comment]
Annoyingly, it's complicated by a few things. Most annoying is:

* http://stackoverflow.com/questions/27607988/django-class-overrides-fails-system-check - `StatusCheckResult` models have a `check` attribute which conflicts with the `check()` classmethod. Requires renaming to get to ≥ 1.7

I'm sure that once that's resolved there will be a laundry list of things. I was hopeful that @bonniejools would be interested in breaking out the upgrade code from other things but that doesn't (yet?) seem to have happened.

**Pull request closed without merging**
