### PR TITLE
Github and Github enterprise single-sign-on

### PR DESCRIPTION
**Pull request by nickromano**
I've done a simple integration with `python-social-auth` to get Github Enterprise SSO working with an Organization whitelist.  I'd be happy to add a page of documentation for this to http://cabotapp.com/qs/quickstart.html but I'm not sure how.

If there is interest I'd be happy to add Github SSO also.

Thanks,
Nick

### CODE REVIEW

**Comment by dbuxton** [comment]
This is awesome @nickromano thanks. +1 for adding standard GitHub. Do you want to put into the same PR or a different one?

To add to the quickstart docs you need to send a pr for the `gh-pages` branch.

**Comment by nickromano** [comment]
@dbuxton No problem I'll add Github to the same PR and link a PR for the docs!

**Comment by nickromano** [comment]
@dbuxton Github SSO and documentation has been added here: https://github.com/arachnys/cabot/pull/504

**Comment by JeanFred** [comment]
That‘s awesome @nickromano − adding social-auth support has been on my Todo forever but never got around doing it. I’ll look into adding Google SSO (since this is what we use at Arachnys) shortly :)

**Comment by frankh** [comment]
Works perfectly, thanks!

**Pull request merged**
