### PR TITLE
Graphite x-range as status check model field

### PR DESCRIPTION
**Pull request by andrewbaxter**
We have some stats that are populated once every minute with a very high resolution, and others updated once every 24 hours with a much lower resolution.  There's no common `GRAPHITE_FROM` that will produce useful graphs for both sets of statistics.
                                                                                
I made these changes:                                                           
- Added `x_range` as a status check field                                       
- Renamed `mins_to_check` to `points_to_check`                                  
- `points_to_check` is now a status check field                                 
                                                                                
The defaults (10 minute `x_range`, 5 `points_to_check`) should match the defaults in an unmodified Cabot installation.

### CODE REVIEW

**Comment by Duologic** [comment]
Looks a lot like https://github.com/arachnys/cabot/pull/127
Points_to_check is an interesting perspective, but is seems to replace the minutes_to_check directive. This makes that the period becomes implicit and harder to find for on call agents that didn't implement the check.

**Comment by aolgin** [comment]
We're running into similar issues when trying to alert on metrics that come in every 4 hours or so. Having such a feature would be incredibly useful for us because we are struggling to find a good workaround.

Something like it being an non-required field in the check that will default to the value of GRAPHITE_FROM, and will use the specified window/x-range if it is there is what I'm currently imagining.

Any update on either this or #127 ? As Duologic said, the two seem to be trying to accomplish the same goal, more or less.

**Comment by dbuxton** [comment]
Sorry that this has been festering for a while. @JeanFred it would be nice to get either this or #127 merged. What do you think?

**Comment by andrewbaxter** [comment]
It's been awhile since I worked on this, but if I recall correctly there were two reasons for changing minutes to points.  

One was that the underlying code was actually checking points without consideration of the range (I think).

The second was so that a single default value would work for any x range ~ a default 10 mins to check works for an x range of 1h, but would not be useful for an x range of 1 week or 5 minutes.

**Comment by dbuxton** [comment]
@andrewbaxter I think this has been solved by https://github.com/arachnys/cabot/pull/366 - can you have a look and see if you think there are any remaining issues?

That is a more robust solution based on actually reading the timestamps from Graphite. I think that deals with the issues you point out but perhaps I'm missing something.

**Comment by andrewbaxter** [comment]
@dbuxton There are two implicit variables being equated in #366 with the explicit period between checks: the period of time to display, and the period of time to test for failure conditions.  This approach is obviously simpler, but it prevents things like checking every 5 minutes for 95% availability for the previous hour (check period = 5m, display = 1h, test points = 1h), or checking the previous day but showing a whole week's worth of data for reference when editing the check (check period = 1h, display = 7d, test points = 1d).

These may not have been goals from the start, but this functionality was at least partially present with `GRAPHITE_FROM`.  The former use case is important to me, and I think explicit options with sane defaults would not harm the user experience.

**Comment by dbuxton** [comment]
@andrewbaxter I see where you're coming from.

The display period is something that I think is pretty reasonable to set globally (although Graphite's inconsistency in displaying different time ranges is annoying) - probably we would want to just provide some method in the UI of switching between different time periods.

I think the default should surely be the check frequency and there should be a per-check setting of `minutes_to_check` or similar that tells each check to look back the specified amount (this will nearly always be > the frequency, or can you think of times that you'd want <=?)

I think we should break out discussion of that into a separate issue - have created #386 as a placeholder

**Pull request closed without merging**
