### PR TITLE
Configurable URL prefix

### LINKED ISSUE #321: Make cabot URL configurable for reverse proxy
I would like to run cabot behind reverse proxy. I configure it to be available via /cabot/ URL. However it redirects to /services/ when I try to access it. 

Is there any way to configure URL prefix for cabot?

### PR DESCRIPTION
**Pull request by imnotjames**
This is a basic implementation to allow the usage of a URL prefix with Cabot, as well as some bug fixes related to the feature.

* Hard-coded Static URLs in templates have been replaced with `{% url "" $}` equivalents
* the `LOGIN_URL` django settings value is set correctly from the `urls.py`
* the URL overriding is updated so we replace django URLs with our own
* add a `URL_PREFIX` environment variable to configure the URL prefix applied to all generated URLs

This resolves #321 and I'm pretty certain it works well enough for me to use Cabot under a reverse proxy in a subdirectory.

However, I have not tested all of the plugins, and I'm not the greatest with Django, so a second set of eyes would be appreciated!

### CODE REVIEW

**Comment by dbuxton** [comment]
@imnotjames this looks great - could we at least add a basic test of some sort?

**Comment by imnotjames** [comment]
Great idea!  I'll try to figure out how the testing infrastructure works.

**Comment by imnotjames** [comment]
@dbuxton I added a test case but I'm not sure what all I should be testing with this exactly.  If there's anything else I should be checking for please point me in the right direction.

**Comment by m-brown** [comment]
Thank you @imnotjames for the enhancement; it looks fine to me and testing everything worked as expected.

**Comment by edwardmp** [comment]
Does this feature still work? I'm running Cabot behind a reverse proxy and it tries to redirect to the URI without said port.

I tried setting `URL_PREFIX=:8111` (cabot originally runs on :8080) but get Django 404 errors using this approach: `Page not found (404) Using the URLconf defined in cabot.urls`

**Comment by dbuxton** [comment]
Hi @edwardmp - I'm not totally sure that I understand. So you want to expose a Cabot instance on external port of `8111`?

The port isn't the first part of the path - it's the last part of the hostname. If you visit Cabot on `https://cabothost.com:8111` all the links will be relative to that hostname (i.e. `https://cabothost.com:8111/services/`)

If you just want to change the port that the reverse proxy connects to, you can just set the `PORT` environment variable.

**Pull request merged**
