### PR TITLE
bump celery version (fixes #334)

### LINKED ISSUE #334: possible memory leak with celery processes
Hey, we are currently running 176bac890 using our private fork of https://github.com/shoonoise/cabot-docker and we have an issue where cabot eats more and more memory after running for some time. The culprit seem to be the celery processes:

{code}
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
22260 root      20   0 1431068 797888   3924 S   0.0  9.8  27:13.21 celery
22256 root      20   0  630148 455200   4624 S   0.0  5.6   4:09.47 celery
22245 root      20   0  632920 434316   4616 S   0.0  5.3   4:12.00 celery
22254 root      20   0  634468 432172   4616 S   0.0  5.3   4:11.59 celery
22246 root      20   0  629652 430004   4616 S   0.0  5.3   4:09.68 celery
22249 root      20   0  630468 429840   4616 S   0.0  5.3   4:09.26 celery
22255 root      20   0  628276 429236   4616 S   0.0  5.2   4:07.82 celery
22251 root      20   0  628248 428748   4616 S   0.0  5.2   4:08.29 celery
22259 root      20   0  630904 428668   4616 S   0.0  5.2   4:10.04 celery
22247 root      20   0  630140 428564   4616 S   0.0  5.2   4:09.94 celery
22252 root      20   0  630516 428000   4616 S   0.0  5.2   4:09.41 celery
22248 root      20   0  629856 427748   4616 S   0.0  5.2   4:08.66 celery
22258 root      20   0  629404 427008   4616 S   0.0  5.2   4:07.55 celery
22253 root      20   0  628296 426928   4616 S   0.0  5.2   4:07.59 celery
22250 root      20   0  625588 425296   4616 S   0.0  5.2   4:06.67 celery
22257 root      20   0  624612 423320   4616 S   0.0  5.2   4:05.78 celery
22244 root      20   0  626440 420056   4616 S   0.0  5.1   4:08.28 celery
{code}

After restarting the cabotapp container, it looks very different:
{code}
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 9646 999       20   0  227244 121036 120532 S   0.0  1.5   1:27.74 postgres
26921 root      20   0  182180  57244   8000 S   0.0  0.7   0:02.85 gunicorn
26927 root      20   0  180272  55260   8064 S   0.0  0.7   0:03.13 gunicorn
26924 root      20   0  182072  55156   8092 S   0.0  0.7   0:03.05 gunicorn
26937 root      20   0  176112  48244   8004 S   0.0  0.6   0:00.24 celery
26912 root      20   0  173236  48104   8776 S   0.3  0.6   0:02.84 celery
26945 root      20   0  176128  47348   7088 S   0.0  0.6   0:00.22 celery
26941 root      20   0  176048  47308   7088 S   0.7  0.6   0:00.26 celery
26942 root      20   0  176092  47252   7088 S   0.0  0.6   0:00.22 celery
26935 root      20   0  176072  47236   7088 S   0.3  0.6   0:00.23 celery
26943 root      20   0  176104  47232   7088 S   0.0  0.6   0:00.14 celery
26936 root      20   0  175928  47112   7088 S   0.0  0.6   0:00.24 celery
26934 root      20   0  175900  47096   7088 S   0.3  0.6   0:00.19 celery
26938 root      20   0  175880  47072   7088 S   0.0  0.6   0:00.24 celery
26932 root      20   0  175836  47068   7088 S   0.0  0.6   0:00.30 celery
26944 root      20   0  175800  47032   7088 S   0.0  0.6   0:00.15 celery
26939 root      20   0  175852  46988   7088 S   0.3  0.6   0:00.16 celery
26931 root      20   0  175732  46984   7088 S   0.0  0.6   0:00.23 celery
26930 root      20   0  175716  46956   7088 S   0.0  0.6   0:00.28 celery
26933 root      20   0  175700  46852   7088 S   0.3  0.6   0:00.23 celery
26940 root      20   0  173444  46644   7012 S   0.0  0.6   0:00.17 celery
26946 root      20   0  172852  45832   6732 S   0.0  0.6   0:00.62 celery
{code}

I.e. 0.6% memory vs. 5% memory (the latter even lead to the system swapping).

I found a few issues for "celery memory leak", but all the issues are very old and did not contain enough information for me to take any action.

I don't want to set up a cron job to restart cabot regularly.

Please let me know if you have any suggestions or if I can provide any useful information.

### PR DESCRIPTION
**Pull request by marvinthepa**
kombu also needed a bump as celery depends on it

### CODE REVIEW

**Comment by dbuxton** [comment]
@JeanFred I seem to remember a recent Celery issue with something else - is this OK to merge?

**Comment by marvinthepa** [comment]
Hey @dbuxton, are you waiting for @JeanFred to answer? Looks like he did not read this ;-) - is there also a way this could be implemented without him approving?

**Comment by JeanFred** [comment]
Thanks for the ping @marvinthepa - will look at it now :-)

**Comment by marvinthepa** [comment]
Thanks a lot for looking into this. I have an internal ticket that is
waiting for this, and I want to close it 😀.

**Comment by JeanFred** [comment]
So @dbuxton was referring to a problem we had with another app at Arachnys − a silent upgrade to kombu (which we had not pinned, via celery) was breaking with our version of redis library.

I don’t see how that would be a problem in this case though − tests are passing, Cabot is running − sounds all good :) Merging!

**Pull request merged**
