### PR TITLE
Slack support (references PR #55)

### PR DESCRIPTION
**Pull request by ethervoid**
I've updated the integration of Slack made by @caseycrites in the PR #55:
- Modified the migration to include cabotapp_instance
- Added Icon URL

### CODE REVIEW

**Comment by NuckChorris** [comment]
Any updates on this?  Cabot is basically useless to me without Slack integration, and as more people ditch HipChat in favor of Slack this will only become a bigger issue.

**Comment by dbuxton** [comment]
Sorry have been distracted with all sorts of stuff. Ideally @ethervoid would be able to reimplement as an alert plugin (see e.g. https://github.com/bonniejools/cabot-alert-hipchat) - plugin infrastructure landed a few weeks ago.

**Comment by lblasc** [comment]
Hello guys,

https://github.com/lblasc/cabot-alert-slack I've modified original hipchat plugin to support slack, but I only tested it in ipython, but it should work, it's not on pypi yet, so clone and install the plugin with pip install -e cabot-alert-slack while in cabot virtualenv.

Pull request are welcomed !

**Comment by dbuxton** [comment]
@lblasc thanks for adding this - I will close this as redundant

**Pull request closed without merging**
