### PR TITLE
Json check

### PR DESCRIPTION
**Pull request by frankh**

### CODE REVIEW

**Comment by frankh** [comment]
Todo: tests

**Comment by JeanFred** [comment]
Oh, interesting !

* Can you elaborate in the commit message on the reasons why this new check is useful ?
* Looks like there is some overlap with HTTP check. Could that have been done as part of the HTTP check ?

**Comment by frankh** [comment]
@JeanFred main use case was for stuff like celery stats endpoint (which we have a horrrible regex hack for), and some other hypothetical i can't remember right now. But it's useful for basically anything that exposes a json endpoint

There is a lot of overlap with httpcheck... I was actually thinking of refactoring to have 

 * (Abstract?) http check that only has status code check
 * Regex http check
 * Json http check

Alternatively it could be 1 type of check with a drop-down for check type? would be more front-end work though

**Comment by cwegener** [comment]
This looks very interesting indeed. I am curious to see if this allows me to use events from sensu-api as cabot checks.

**Comment by frankh** [comment]
Closing as it's super out of date.

**Pull request closed without merging**
