### PR TITLE
Update example conf files to hipchat 1.8.3

### PR DESCRIPTION
**Pull request by benoror**
Tag: https://github.com/cabotapp/cabot-alert-hipchat/releases/tag/1.8.3
Related issue: https://github.com/shoonoise/cabot-docker/issues/42#issuecomment-278219518

### CODE REVIEW

**Comment by frankh** [comment]
As far as I no the versions of the plugins in the config files don't actually mean anything.

Only the versions in the requirements-plugins.txt actually matter (and are now updated)

Thanks for the PR but I'm going to close for now and just remove versions entirely from the config

**Comment by frankh** [comment]
Turns out the versions may be used in setup.py, creating a new PR to update all plugins (the twilio and email plugins need updating too)

**Comment by dbuxton** [comment]
Yes it makes sense I think to get them out of requirements-plugins.txt, otherwise it'll be difficult to set up a pure docker deploy without source changes.

**Comment by JeanFred** [comment]
> Yes it makes sense I think to get them out of requirements-plugins.txt, otherwise it'll be difficult to set up a pure docker deploy without source changes.

Not necessarily ; the way Sentry does it is to use an ONBUILD directive to conditionally install plugin

**Pull request closed without merging**
