### PR TITLE
Serve /favicon.ico resembling current arachnys/img/icon_*x*.png files

### PR DESCRIPTION
**Pull request by hartwork**
One of the effects is that you don't get this Django error e-mail any more:
> ```
> [Django] ERROR: "GET /favicon.ico HTTP/1.0" 500 106
> ```

`.ico` was auto-created as following:
```
$ ( cd cabot/static/arachnys/img && convert icon_*x*.png favicon.ico && file favicon.ico )
favicon.ico: MS Windows icon resource - 2 icons, 48x48, 32 bits/pixel, 96x96, 32 bits/pixel
```

### CODE REVIEW

**Comment by hartwork** [comment]
Any concerns or thoughts about this pull request?

**Comment by hartwork** [comment]
@frankh @dbuxton do you have a minute?

**Comment by dbuxton** [comment]
maybe it's overkill but we should really have a test to confirm that favicon is served with status code 200. Could you add that?

**Comment by hartwork** [comment]
Added a simple test and rebased against current master. I refrained from using `reverse` as this use is a lot more clear in my eyes (and the path won't change).

**Comment by hartwork** [comment]
I'm not sure why CI fails, the test passes for me:
```
# docker-compose run web python manage.py test cabot.cabotapp.tests.tests_basic.TestWebInterface.test_favicon_ico
Starting cabot-git_redis_1 ... done
Operations to perform:1    ... done
  Apply all migrations: admin, auth, cabot_alert_email, cabot_alert_hipchat, cabot_alert_slack, cabot_alert_twilio, cabotapp, contenttypes, sessions, sites
Running migrations:
  No migrations to apply.
Copying '/code/cabot/static/arachnys/img/favicon.ico'
Found another file with the destination path 'admin/js/jquery.init.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.

1 static file copied to '/code/cabot/.collectstatic', 401 unmodified.
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.
----------------------------------------------------------------------
Ran 1 test in 0.259s

OK
Destroying test database for alias 'default'...
```
Is this `NoReverseMatch: Reverse for 'user-profile' with arguments '(None,)' not found. 1 pattern(s) tried: ['user/(?P<pk>\\d+)/profile/$']` thing related?

**Comment by hartwork** [comment]
Tests fixed now, please have a second look.

**Pull request merged**
