### PR TITLE
Custom HTTP headers.

### PR DESCRIPTION
**Pull request by iurisilvio**
Ref #242 

Support any HTTP header, in response to #269 request.

The HTTP header must be a JSON object.

### CODE REVIEW

**Comment by dbuxton** [comment]
This looks great @iurisilvio - two (somewhat related) questions:

* do you think it's worth including a custom widget (e.g. http://www.huyng.com/posts/django-custom-form-widget-for-dictionary-and-tuple-key-value-pairs/) or is it OK to ask users to use JSON?
* It doesn't look like we are validating the JSON input. That means that if the input isn't valid JSON the checks are going to error out. I think we should use something like https://github.com/bradjasper/django-jsonfield to ensure that what goes into the database is acceptable.

**Comment by iurisilvio** [comment]
Yes! Definitelly it is a good thing to do. First, I decided to add only the Host because I didn't found a good solution to set multiple key/values.

I'll take a look at django-jsonfield and how to add it to cabot.

**Comment by pradex** [comment]
Hi, 
I am facing a similar issue while setting up an alert, can you guys please help me with timeline with above discussed change, when can I expect this to be pushed into master repo?

**Comment by iurisilvio** [comment]
@pradex I never implemented the `django-jsonfield` part. I don't think it has a timeline to merge.

**Comment by pradex** [comment]
So is there a way around to solve this problem of adding header or If you can give me some heads-up then I'll try to fix it for my use-case? 
Thanks

**Comment by iurisilvio** [comment]
I think this pull request works to set `Host` header. You can just merge it and use a custom cabot codebase.

It was not merged because @dbuxton suggested to make it generic to set other headers. I agree with him, but didn't had time to continue the work.

**Comment by vtrbtf** [comment]
👍

**Comment by frankh** [comment]
I'm closing old unmerged PRs with conflicts.

Even though this doesn't technically have a conflict, it's using old south migrations so will not merge nicely to master.

Feel free to re-open if you feel it's still relevant

**Pull request closed without merging**
