### PR TITLE
Cabot check plugins

### PR DESCRIPTION
**Pull request by bonniejools**
Thought that I would create a new PR for check plugins. Obviously this branch is only a couple of days old however things are coming along alright. There is a 'template context processor' which lists available checks in the navbar.

There is also another repo called cabot-check-icmp which is an example check plugin for ping requests. I'll update as I progress.

### CODE REVIEW

**Comment by sijis** [comment]
I'm really interested in the progress of this feature. Is there any progress on this or anything I could do to help?

**Comment by dbuxton** [comment]
I think @bonniejools abandoned @sijis so if you'd like to contribute (or start from scratch) the help would be much appreciated.

In general my responsibilities at Arachnys are preventing me from putting as much time into Cabot as I would like (i.e. any time) so if anyone would like to volunteer to help maintain the project I'd be very interested. We will continue to invest but inevitably we're focused on features that directly benefit us :(

Let me know @sijis if you want to add to this PR or create a new one.

**Comment by as-sergey-m** [comment]
@dbuxton Hello. We use your Cabot monitoring system. For our project, we need to extend http checker, and also need to implement some more checker plugins. It seems that Cabot doesn't have possiblity to build it with custom check plugins.
We want to implement such functionality ourselves and put it on github.
Could you please supply us with instructions of how could we do it properly? What possible problems should we take in mind? 
Feel free to supply us with instructions which will speed up implementation and reduce the chance for errors.

**Comment by dbuxton** [comment]
I think the check infrastructure itself is pretty straightforward to extend. The main challenge is going to be auto-population of e.g. "Add ____ check" functionality. At the moment it's hard-coded (see e.g. https://github.com/arachnys/cabot/blob/2258511c18906afce81f20acc3c930242753d920/cabot/templates/base.html#L67). It's not at all hard but it does require quite a lot of changes.

At the moment all the different check types are "proxy" models, meaning that they have the same implementation in the database. Due to the fact that polymorphism in Django is a nightmare, I'd be reluctant to extend that. However interested in other people's views there.

I'd be inclined to aim, eventually, for the same plugin/module mentality as the alert plugins, but perhaps as an immediate goal short of that, we could break out the checks into a separate directory structure and have the directory structure automatically populate. That could give a pretty painless migration path. 

@frankh @JeanFred what do you think? @bonniejools I know you have thought a lot about this in the past...

**Comment by as-sergey-m** [comment]
Here is my implementation of custom check plugins feature https://github.com/arachnys/cabot/pull/527
Please, check it out

**Pull request closed without merging**
