### PR TITLE
added custom check plugins feature

### PR DESCRIPTION
**Pull request by as-sergey-m**

### CODE REVIEW

**Comment by dbuxton** [comment]
Thanks! I'll leave @frankh and @JeanFred to comment on substance.

How do you feel about migrating the existing checks to use this infrastructure? Wouldn't that make sense?

**Comment by as-sergey-m** [comment]
> How do you feel about migrating the existing checks to use this infrastructure? Wouldn't that make sense?
Yes, that would make sense as part of refactoring (like dividing models, templates and views into separate modules by functions), but we are not ready to work on it

**Comment by as-sergey-m** [comment]
Will add link to skeleton check plugin we've used a bit later

**Comment by as-sergey-m** [comment]
Here is skeleton plugin we used to test with this feature https://gitlab.com/as-public/cabot-check-skeleton

**Comment by dbuxton** [comment]
Can we add something to the readme explaining how to write a custom check plugin? 

I've created #529 as a suggestion that we migrate all checks to use this architecture.

**Pull request merged**
