### PR TITLE
If statement wasn't checking for None correctly, which made failures …

### PR DESCRIPTION
**Pull request by crucial7**
…"pass" when they shouldn't have.

### CODE REVIEW

**Comment by dbuxton** [comment]
PR looks good but we should fix this test - let me know if you'd like to, @crucial7

**Comment by crucial7** [comment]
I'll see if I can work on the test at some point and I'll let you know when
it's fixed.

**Comment by dbuxton** [comment]
Done already

**Comment by crucial7** [comment]
Ok great!

**Pull request merged**
