### PR TITLE
Determine Graphite Check Range by Frequency

### PR DESCRIPTION
**Pull request by bbonf**
I was having a problem checking metrics that update less frequently than the default 10 minutes.

I could have increased the global GRAPHITE_FROM but I preferred the range to be determined by the check's frequency.

This PR also makes the metric preview graph show the correct range as the frequency is modified.

### CODE REVIEW

**Comment by Duologic** [comment]
I've seen this issue happen several times, mostly when using the summarize() function.
:+1: from my end.

**Comment by grzegorz-dubicki** [comment]
+1

**Comment by carande** [comment]
I'm encountering this issue as well (metrics of varying timescales), and would be very interested in this feature!

**Comment by frankh** [comment]
Cleaning up old PRs

Feel free to re-open with the conflicts resolved if you think it's still relevant

**Pull request closed without merging**
