### PR TITLE
Adds the 'EMAIL_USE_TLS' option to the settings file.

### LINKED ISSUE #277: Support for STARTTLS over smtp
It would be nice to support STARTTLS over smtp (explicit tls).
This is a matter of adding the following setting:

EMAIL_USE_TLS = 1

See this site for details https://docs.djangoproject.com/en/1.8/ref/settings/

### PR DESCRIPTION
**Pull request by movermeyer**
Resolves #277

### CODE REVIEW

**Comment by dbuxton** [comment]
@JeanFred we OK to merge this?

**Comment by josegonzalez** [comment]
:+1:

**Comment by luxifer** [comment]
Please... :+1:

**Comment by JeanFred** [comment]
Thanks for the pull-request @movermeyer !

**Pull request merged**
