### PR TITLE
added google login, is_public flag to services, and public view for m…

### PR DESCRIPTION
**Pull request by pablodgonzalez**
…arked services, added base_public.html for unauthenticated users and use that with authenticated views.

Hi @dbuxton, In SENZIL we are beginning to use cabot for monitoring some of ours services.
We've made a fork to add some features and we thought of some of those could be useful for all.

- We've added google login, furthermore, we've add social buttons in the login view through an template, so, now is easier add other social logins (bitbucket, gitlab, etc)
-  We've added the field "is_public" to the service model to mark a service for public access
- A Service list (with basic information for public access) in our case we will put cabot public for ours clients
- We've added a base_public.html template for views of non authenticated users (login, logout, service public list)

Now, we will use our docker image from our fork, but we think will be great if this features become part of cabot.
And we have other ideas for make cabot more flexible for an easier configuration and customization.

Cheers

### CODE REVIEW

**Comment by JeanFred** [comment]
Hi @pablodgonzalez − this looks fantastic! I have had a look and this looks great to me. I think these are features we would love to integrate in Cabot

Can you have a look at the Travis failures?

There are two flake8 violations:
```
./cabot/urls.py:48:3: E111 indentation is not a multiple of four
./cabot/urls.py:50:3: E111 indentation is not a multiple of four
```

There are also 13 test failures − could you look into it? Not sure what’s happening there (just having a quick look during holidays ;-)

**Comment by JeanFred** [comment]
Hi @pablodgonzalez I have tested the public service thin locally − works fine. I would have just one question : on the services public page, the service is hyperlinked, but the link appears to go nowhere?

**Comment by pablodgonzalez** [comment]
@JeanFred I used the url field from service model
<a href="{{service.url}}" title="{{service.url}}">{{service.name}} </a>
The idea is define some public and useful url for the people.
If you wish, I can change to another thing

**Comment by JeanFred** [comment]
> @JeanFred I used the url field from service model
> The idea is define some public and useful url for the people.

Oh I see! I had not defined any URL for my test service so the link was going nowhere. I agree your solution makes sense. It’s a bit confusing if no URL is defined, but not sure this is common use case. In any case I don’t think it should be blocking merging this.

**Comment by JeanFred** [comment]
This is now merged! Thanks again for your contribution @pablodgonzalez. If you folks at Senzil have other cool stuff that could be upstreamed by all means please do!

**Pull request merged**
