### PR TITLE
Allow non-embed links for recovery instructions and automatically create Django profiles

### LINKED ISSUE #273: Allow non-embed links for recovery instructions
Every company has their own style of wikis, with pages that can generally be reached via generic https urls.  

If recovery instructions could just be generic links, it would allow teams considering Cabot to leverage existing wiki documentation.

### PR DESCRIPTION
**Pull request by cmclaughlin**
@dbuxton:

Adding a new field for linkable recovery instructions, i.e. a link to a
runbook on the company's wiki.

A few notes/things to point out in this change:

* I expanded form field widths on the service and instance pages...
  I had to add a new field and it was really small by default, so I made
  all the widths match because I think it looks better.

* The InstanceForm class had hackpad_id defined as a field, but not as a
  widget, so it wasn't visiable.  I think that was a mistake, so I
  cleaned it up. For most users I don't think it make sense to have
  documentation for particular instances, so removing it seems like the
  right thing to do.

Closes #273

### CODE REVIEW

**Comment by cmclaughlin** [comment]
I think there's a bug in this..  I'll try to fix it soon.

**Comment by cmclaughlin** [comment]
Well, I thought I might have introduced a bug... not after taking a closer look I don't think so.  Some combination of submitting the update form and going 'back' in the browser can introduce "None" into the hackpad_id field.  But the form validation catches that, so it never makes it into the DB.

That showed me I should add form validation to the runbook_link field I'm introducing that... so I just added that with a second comment.  Please let me know if you'd like them squashed.

**Comment by cmclaughlin** [comment]
Actually I think I anded up with "None" in the hackpad_id field by adding resources with the API.  So I think this PR is OK

**Comment by JeanFred** [comment]
This looks very good @cmclaughlin (especially as we moved away from Hackpad at Arachnys, and now we need to link to our new system as we cannot embed it!).

I tested this locally and it works fine for me.
 
* Can you please solve the merge conflicts? I merged a cleanup PR earlier which causes a lot of merge conflicts :-/ (you can squash at the same time ; but now that can be done via Github itself :)
* Might be a but overkill but would it be possible to have a test for this new `clean_runbook_link` method?

Thanks!

**Comment by cmclaughlin** [comment]
Thanks... I will try to work on this soon.

**Comment by cmclaughlin** [comment]
@JeanFred sorry for the delay.  I just got around do updating this.  I also merged PR #329 with this... that allows me to test all these changes on my instance.  I also spun up a new VM and tested a fab provision/deploy.  My changes work as expected... and I don't think I broke anything else.

**Comment by JeanFred** [comment]
@cmclaughlin Sorry for the delay too − I will review this in the next seven days :)

**Comment by JeanFred** [comment]
I just deployed this locally − went like a charm, and works as expected. There has been another migration in the meantime so number 17 is already taken − can a Django master ( @m-brown or @mrsaints ?) remind me whether that is a problem or not?

**Comment by m-brown** [comment]
@JeanFred yes it can be but it's easily fixable; remove the migration and re-run migration command and that will generate a new migration with the right number.

**Comment by JeanFred** [comment]
This is now merged − I somehow got lost into a succession of rebase / merge -no-ff / rebase and lost the merge commit linking to this >_>

Thanks again for your work − and your patience − @cmclaughlin !

**Pull request closed without merging**
