### PR TITLE
pagination and search for instances and checks

### PR DESCRIPTION
**Pull request by iliyanotlioneberia**
If you have a lot of instances with a lot of checks this will significantly reduce the time instance.html and checks.html loads. With added search field it will make some tasks faster.
There is a js pagination for checks right now but this will still load all objects from postgresql and then paginate on the fly thus time consuming

screen shot 2015-12-11 at 16 28 33

screen shot 2015-12-11 at 16 28 57

screen shot 2015-12-11 at 16 28 48

### CODE REVIEW

**Comment by josegonzalez** [comment]
@dbuxton any chance we can land this PR instead of #292?

**Comment by benroeder** [comment]
could we merge this.
We have 1000's of instances that we test, and the JS approach just loads the whole lot in one go, and times out. With django pagination approach you can have as many as you want and scales

**Comment by dbuxton** [comment]
@jeanfred can you look?

**Comment by JeanFred** [comment]
Sorry for the delay in getting back to you @iliyanotlioneberia. This will be reviewed in the next seven days. Thanks for your patience!

**Comment by m-brown** [comment]
Hi @iliyanotlioneberia, we really appreciate you taking the time to create this patch. We agree with the use case and think it's a great idea but we have some concerns around how it is implemented. In particularly we think it would be easier to maintain using the more standard way of implementing pagination in django [1]; specifically a) using the standard paginator and using a for loop in the template to generate the pagination links in the template, and b) using the paginator to restrict the queryset before evaluating it to prevent loading all instances/checks on each page load. We are going to close this but would love to see you open a new patch that takes the above direction. Thanks, this will be a really useful feature.

[1]  https://docs.djangoproject.com/en/1.10/topics/pagination/#using-paginator-in-a-view

**Pull request closed without merging**
