### PR TITLE
Cabot alert plugins

### PR DESCRIPTION
**Pull request by bonniejools**
Not expecting a merge right now. Just letting you know how the plugin architecture is going. [the user preference page](http://i.imgur.com/BIUYRx1.png) has been completely overhauled and has complete support for plugins. It doesn't render properly on mobile. Is that a target platform? If so I can try and make it work.

* All tests are failing to the point that they won't even run at the moment - let alone pass.
* There is currently no way to migrate.
* Documentation still needs to be written.

### CODE REVIEW

**Comment by dbuxton** [comment]
@bonniejools I think we need to have a clear upgrade path, even if it's just a script that pulls across data from one install to the next. Otherwise it's going to be pretty annoying for people to recreate their entire installs.

I'm not sure why we need to delete existing migrations here? Can't we just deprecate the existing database fields and leave for posterity?

**Comment by bonniejools** [comment]
@dbuxton yeah, I'll remerge the migrations.

An upgrade path could be written straight into the fabfile I think. Might be able to get away with it without any intervention from the end user. I'll look into it.

**Comment by dbuxton** [comment]
That would be great, but we should make sure it's tested if that's the
promise we are making

**Comment by bonniejools** [comment]
migrations remerged

**Comment by bonniejools** [comment]
Clean installs are now working. I have begun work on the data migrations.

**Comment by dbuxton** [comment]
@bonniejools great, would be good to squash it down into something a bit more monolithic when we are close to being able to merge...

**Comment by bonniejools** [comment]
@dbuxton that sounds like a good idea; they're getting a little out of hand.

**Comment by bonniejools** [comment]
tests are now passing and the the [travis build](https://travis-ci.org/bonniejools/cabot) is passing as well.

**Comment by dbuxton** [comment]
@bonniejools great news! I've added some specific comments on bits of your code that look a bit strange, but seems we're nearly there.

One question: do we have any tests for the migrations themselves so that we can very the upgrade functionality?

Let's ensure that the individual alert modules are being tested properly and once we've rubbed off some of the rough edges it would be great to get this pushed up and some docs written on how to write your own plugin.

**Comment by bonniejools** [comment]
The data migrations are now working on my machine. I've tested it with my own databases but I'll see if I can write some general tests.

**Comment by dbuxton** [comment]
I'd be OK with the approach outlined in the first answer here: http://stackoverflow.com/questions/8798868/testing-south-migrations-in-django

It doesn't look like there's any more formal way of doing it but as long as we check the right data is being copied across it should be OK.

**Comment by bonniejools** [comment]
[Putting the tests into the data migrations](http://stackoverflow.com/a/10277016) seems like a really good idea. I'll do that today.

**Comment by bonniejools** [comment]
The user data migrations are now tested in 0011_plugin_data_migration_tests.py

**Comment by dbuxton** [comment]
Great, can we please
* Squash this
* Update so that it will merge cleanly with HEAD
* Update docs

I will merge into `dev` and then we will merge across into `master` - OK?

Good work... Now all we need to look at is monitor plugins...

**Comment by packetcollision** [comment]
I've got a [Pushover](https://pushover.net) plugin working. It ended  up being really simple to do, so thanks for making the process easy. 

Is there going to be a list of available plugins? If so, count me in. I'd also love to hear any feedback you might have about how I did it.

**Comment by dbuxton** [comment]
@packetcollision great work, this is exactly what we were going for. Now, if we can just 

Can I ask: did you successfully upgrade an existing install with the migrations in this PR, or did you start with a fresh one?

**Comment by ethervoid** [comment]
Really good work guys! Sadly I couldn't work on this but I'll glad to help from now on :)

**Comment by dbuxton** [comment]
and @packetcollision yes we'll put a list of plugins in the readme and on [the project site](http://cabotapp.com) as soon as the plugin infrastructure hits master

**Comment by bonniejools** [comment]
@packetcollision nice work. Happy to hear your feedback as well. This PR is subject to change a small bit over the next couple of days as it moves towards release so I would avoid using this branch in production just yet.

**Comment by packetcollision** [comment]
@dbuxton I seemingly successfully migrated my local development environment and "production" (in quotes because it's a non-critical system) install on 752e38d but when I checked out c428041 and attempted to `fab deploy` again (or just ran the migrations on my dev environment), I got a [stack trace](https://gist.github.com/packetcollision/4c45494479f9be879fd5) when trying to run the migration tests: `cabot_alert_email.models.MultipleObjectsReturned: get() returned more than one EmailAlert -- it returned 2!`. Commenting out the foreman migration line in the Fabfile let the deploy complete, and since I had already done the migrations successfully on the old commit, it worked as well as before. On both of the SHAs I tested, in both dev and prod, I see both "Email" and "Email Plugin" alert options, so I assume there is something wrong with the email data migration

@bonniejools The only thing I have found tricky about the plugin architecture so far is that you have to edit `setup.py` as well as `conf/<environment.env` to add the enabled plugins if you want the fab deploy to work. I really think editing a single file should be enough, and having to edit `setup.py` is especially problematic because it means your repo is modified so you have to do `git stash && git pull && git stash pop` every time you want to update.  It's only [a few lines of code](https://gist.github.com/packetcollision/225afc02537dc74cd48e) to make setup.py read `CABOT_PLUGINS_ENABLED` out of the environment and install the plugins specified there, but it doesn't have versions and requires running the initial pip install with foreman even on local dev. I'm not sure if you want to go down that route, but I found it useful.

**Comment by bonniejools** [comment]
@packetcollision Thanks for that bug report, very in depth and useful. I renamed the email plugin about a week ago so that it would fit in with the naming scheme of the others. Obviously I must have missed something.

You can enter the virtualenv on the server with

    $ . venv/bin/activate

and then install your plugin via pip if you don't want to edit the setup.py. Obviously this isn't ideal if you're deploying to multiple servers.

**Comment by dbuxton** [comment]
@bonniejools I think @packetcollision 's [way](https://gist.github.com/packetcollision/225afc02537dc74cd48e) of getting the enabled plugins installed is elegant, anything we can do to reduce the number of files that people have to edit is great...

**Comment by bonniejools** [comment]
@dbuxton I'll merge it

**Comment by dbuxton** [comment]
@bonniejools this is all good and I've tested the upgrade path from current master - I'm happy to merge in once it has been [rebased and squashed](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) - assuming that's possible given that you've merged in upstream changes. Can you give it a go?

**Pull request merged**
