### PR TITLE
Exposing check status to API

### PR DESCRIPTION
**Pull request by yigitbey**
Adding check status & overall service status to API

### CODE REVIEW

**Comment by movermeyer** [comment]
@yigitbey, I would like this feature and I'm willing to make a new PR for it, but before I spend that effort, was there a reason (besides time) that this was not completed?

**Comment by dbuxton** [comment]
I think it just fell through the cracks @movermeyer - it looks like @yigitbey didn't have time to update test expectations as I requested, and I haven't had time...

**Comment by movermeyer** [comment]
Alright,
I've made the change and [created a pull request for it](https://github.com/arachnys/cabot/pull/252).

**Comment by JeanFred** [comment]
With #252 merged, this can be closed.

**Pull request closed without merging**
