### PR TITLE
Add support for authentication with LDAP

### PR DESCRIPTION
**Pull request by miguel250**

### CODE REVIEW

**Comment by dbuxton** [comment]
Can you fix the test failures @miguel250 ? Just looks like a missing requirement (if you look in `settings.py`)

**Comment by dbuxton** [comment]
`s/settings/setup`

**Comment by miguel250** [comment]
@dbuxton this is fixed. Sorry about that.

**Comment by heta89** [comment]
Hi,

How can I add a user from LDAP in Cabot thru the UI?
I don't see any option.
Add user button gives me option to add only internal user.

I also tried logging it to Cabot using LDAP credentials but I get invalid credentials error.

Can't find any LDAP configuration related info at http://cabotapp.com/qs/quickstart.html as well.

Can anybody please help with this?

- Heta

**Comment by JeanFred** [comment]
@heta89 Cabot configuration is done for the most part using the configuration file. The bits regarding LDAP, based on this PR, are 
```
AUTH_LDAP=true
AUTH_LDAP_SERVER_URI=ldap://ldap.example.com
AUTH_LDAP_BIND_DN="cn=Manager,dc=example,dc=com"
AUTH_LDAP_BIND_PASSWORD=""
AUTH_LDAP_USER_SEARCH="ou=People,dc=example,dc=com"
```

**Comment by heta89** [comment]
Thanks JeanFred,

So, does it mean that if this is configured properly, I should be able to login using my LDAP credentials?

I configured these fields and I know the values are correct because the same configuration works with another tool.

- Heta

**Comment by heta89** [comment]
Also, is there any configuration on Cabot UI? 
Does Cabot have utility to add/on-board users from Active directory and provide them different permissions?
I'd like to use internal groups with LDAP users.

**Comment by dbuxton** [comment]
Not sure about the details here - @miguel250 was the original author of this - any thoughts?

**Comment by heta89** [comment]
Thanks Dbuxton for your prompt reply.
Hi @miguel250, please have a look at this issue and let me know if i need to change some settings.

i've configured below section and restarted Cabot.
AUTH_LDAP=true
AUTH_LDAP_SERVER_URI=ldap://ldap.example.com
AUTH_LDAP_BIND_DN="cn=Manager,dc=example,dc=com"
AUTH_LDAP_BIND_PASSWORD=""
AUTH_LDAP_USER_SEARCH="ou=People,dc=example,dc=com"

When I compare this with other tools we are using -
Search filter in other tools is - search filter = "sAMAccountName={0}"
whereas in Cabot, it is '(uid=%(user)s)' (ldap.SCOPE_SUBTREE field)

**Comment by miguel250** [comment]
Hi @heta89,

> Also, is there any configuration on Cabot UI?
> Does Cabot have utility to add/on-board users from Active directory and provide them different permissions?
> I'd like to use internal groups with LDAP users.

[django-auth-ldap ](https://pythonhosted.org/django-auth-ldap) has support to mapping LDAP groups to Django permissions but this settings were never exposed to cabot. https://pythonhosted.org/django-auth-ldap/users.html#easy-attributes

> When I compare this with other tools we are using -
> Search filter in other tools is - search filter = "sAMAccountName={0}"
> whereas in Cabot, it is '(uid=%(user)s)' (ldap.SCOPE_SUBTREE field)

I opened a new PR (#482) to make `(uid=%(user)s)` configurable. I hope it helps.

**Comment by heta89** [comment]
Thanks!

**Pull request merged**
